export const radarData = {
  Indeferimentos: {
    number: 186,
    maxValue: 195,
    maxValueName: "2ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 113.5,
    percentage: 0.95,
    variation: -0.046,
  },
  Instaurações: {
    number: 14,
    maxValue: 81,
    maxValueName: "3ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 28.0,
    percentage: 0.17,
    variation: -0.82,
  },
  TAC: {
    number: 0,
    maxValue: 2,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 0.0,
    percentage: 0.0,
    variation: 0.0,
  },
  Ações: {
    number: 3,
    maxValue: 4,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 1.5,
    percentage: 0.75,
    variation: 1.0,
  },
  Arquivamentos: {
    number: 201,
    maxValue: 263,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 149.5,
    percentage: 0.73,
    variation: -0.25,
  },
  "Instauração NF": {
    number: 34,
    maxValue: 34,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 5.6,
    percentage: 1.0,
    variation: -0.82,
  },
  Recomendação: {
    number: 5,
    maxValue: 6,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 1.58,
    percentage: 0.83,
    variation: -0.16,
  },
  "Instauração PA": {
    number: 22,
    maxValue: 22,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 6.8,
    percentage: 1.0,
    variation: 0.0,
  },
  Ofício: {
    number: 497,
    maxValue: 497,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 248.0,
    percentage: 1.0,
    variation: 0.0,
  },
  Reunião: {
    number: 7,
    maxValue: 25,
    maxValueName: "1ª PROMOTORIA DE JUSTIÇA DE TUTELA COLETIVA DO NÚCLEO MACAÉ",
    average: 7.9,
    percentage: 0.28,
    variation: -0.72,
  },
};
